// TODO Implement this library.// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAennZkc10ftFyE6yze8z40V8cz3T286Pc',
    appId: '1:135514514011:web:969b17cb9eafe05e74157e',
    messagingSenderId: '135514514011',
    projectId: 'chatworld-65018',
    authDomain: 'chatworld-65018.firebaseapp.com',
    storageBucket: 'chatworld-65018.appspot.com',
    measurementId: 'G-YS63WVWKYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDns9XamwgqNL-TIiI_GENS0suA-xwgcuA',
    appId: '1:135514514011:android:5cb275c6e3c5e6b774157e',
    messagingSenderId: '135514514011',
    projectId: 'chatworld-65018',
    storageBucket: 'chatworld-65018.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXBjGDklpyG5g8KijTRt5m60ykbuLBMeQ',
    appId: '1:135514514011:ios:b0f44d03801cb0d674157e',
    messagingSenderId: '135514514011',
    projectId: 'chatworld-65018',
    storageBucket: 'chatworld-65018.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXBjGDklpyG5g8KijTRt5m60ykbuLBMeQ',
    appId: '1:135514514011:ios:b0f44d03801cb0d674157e',
    messagingSenderId: '135514514011',
    projectId: 'chatworld-65018',
    storageBucket: 'chatworld-65018.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

}